# Generated by Django 4.1 on 2022-08-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('score', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'users',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='TotalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('total_score', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'users',
                'ordering': ['user'],
            },
        ),
    ]
